### ISSUE TITLE
terminal control artifacts w/ ptpython (prompt_toolkit?)

### ISSUE THREAD

**Issue by yarko** [asciinema/asciinema#194] opened 2017-02-22 20:57 UTC
recording vs playback when using `ptpython` as a repl being recorded works pretty well (even as the file size is large) --- but for newlines after a repl command is evaluated:  there are terminal control artifacts.

the playback pattern emitted (which is not part of the recording) is, for example, of the form:

    ^[[{n};1R

where {n} is some variable number (I've seen, briefly, {18..22}).

As a sanity check, it seems to work ok with `bpython`.

asciinema pip installed version 1.3.0, under python 3.6.0 on ubuntu 16.04

**Comment by sickill** [comment] 2017-02-22 21:05
I think this may be related to #108.

**Comment by tiagocoutinho** [comment] 2017-02-23 16:09
I pretty sure it is the same as #192. Although #192 might be related to #108.

**Comment by mattdeckard** [comment] 2017-03-24 15:49
This is definitely a duplicate of #192 which is itself a duplicate of #108. I suggest closing this issue and #192 and focusing on #108.

**Closed** 2017-03-25 12:40 UTC
