### ISSUE TITLE
Set terminal size while playing

### ISSUE THREAD

**Issue by Irides-Chromium** [asciinema/asciinema#210] opened 2017-05-26 04:21 UTC
While playing another video, the program should set the terminal size according to the description section in the json file, and set the size back to the original when the video is over. For instance, when I was playing a readline library example, the video's terminal size is wider, so there was problems in the playback. The original asciicast is attached. My terminal was 80x24. You can resize your terminal and play the video to see the problem. Thanks!
[asciicast-84610.json.txt](https://github.com/asciinema/asciinema/files/1030809/asciicast-84610.json.txt)

**Comment by sickill** [comment] 2017-06-11 10:00
This is a duplicate of #198 .

**Closed by sickill** 2017-06-11 10:00 UTC
