### ISSUE TITLE
asciinema changes shell behaviour

### ISSUE THREAD

**Issue by mlorenzo-stratio** [asciinema/asciinema#219] opened 2017-08-24 09:54 UTC
This command gets stuck only when running inside asciinema:
```cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 40 | head -n 1```
It works perfectly under a shell.

**Comment by sickill** [comment] 2017-08-31 09:09
That's interesting. I am able to reproduce it on the latest version (1.4).

🤔

**Comment by markasoftware** [comment] 2017-10-17 04:12
I have experienced the same issue with `tr -dc a-zA-Z0-9 < /dev/urandom | head -c 20`. It's very strange, doing head directly on /dev/urandom works fine, and doing tr without piping output also works fine. As I understand it this is a common way to get random values in a shell script, so this really should be fixed.

**Comment by markasoftware** [comment] 2017-10-18 01:04
This does not appear to occur in certain shells. It does occur in Bash, but `asciinema rec -c zsh` works without error. Zsh is mostly compatible with Bash, so in most situations this can be worked around by simply recording a zsh session.

**Comment by sickill** [comment] 2017-10-18 07:23
Thanks for the update @markasoftware. I'm not sure what exactly is happening here, but I suspect this has something to do with our PTY recorder: https://github.com/asciinema/asciinema/blob/develop/asciinema/pty_recorder.py

**Comment by sickill** [comment] 2017-11-26 00:15
I'm no longer able to reproduce that on current `develop` branch. Can you try @markasoftware and @mlorenzo-stratio ? Here's how to run it from git: https://github.com/asciinema/asciinema#running-latest-version-from-source-code-checkout

**Comment by markasoftware** [comment] 2017-11-26 00:21
Still does not work for me on develop branch. Behavior is the same as before.

**Comment by sickill** [comment] 2017-12-02 18:20
I think this may be related: https://github.com/ansible/ansible-modules-core/issues/2305#issuecomment-164170222

**Comment by sickill** [comment] 2017-12-02 19:02
If it's about signal handling (like mentioned in the above linked comment) we may be doing something wrong here: https://github.com/asciinema/asciinema/blob/1e5e20b21381fbbd60ab05a986d0b26f464d59dc/asciinema/pty_recorder.py#L100-L109

**Comment by LuckyDenis** [comment] 2019-05-07 12:11
Good afternoon. I'm on version 2.0.2 to reproduce failed. Already fixed?

**Comment by sickill** [comment] 2022-02-20 15:20
This seems to be fixed now, cannot reproduce anymore.

**Closed by sickill** 2022-02-20 15:20 UTC
Labels: bug
