### ISSUE TITLE
asciinema does not provide a wrapper

### ISSUE THREAD

**Issue by carnager** [asciinema/asciinema#173] opened 2016-08-01 00:02 UTC
Since asciinema is now installed in python's site-packages directory, the binary won't be in $PATH anymore. 

asciinema should probably provide a little wrapper to be placed in $PATH. I guess setup.py is the place to do this.

**Comment by sickill** [comment] 2016-08-02 14:06
Duplicate of #174.

**Closed by sickill** 2016-08-02 14:06 UTC
