### ISSUE TITLE
Cannot play recorded plays in installed asciinema. Is something had broken?

### ISSUE THREAD

**Issue by dmi3mis** [asciinema/asciinema#413] opened 2020-08-02 13:56 UTC
Hi!
I installed asciinema in RHEL7 from EPEL.

[root@testvm student]# rpm -q asciinema
asciinema-1.4.0-2.el7.noarch
[root@testvm student]# asciinema auth
Open the following URL in a browser to register your API token and assign any recorded asciicasts to your profile:
https://asciinema.org/connect/token-was-here
[root@testvm student]# asciinema rec
~ Asciicast recording started.
~ Hit Ctrl-D or type "exit" to finish.
[root@testvm student]# qwqwe
bash: qwqwe: command not found
bash: afasdf: command not found
[root@testvm student]# exit
~ Asciicast recording finished.
~ Press <Enter> to upload, <Ctrl-C> to cancel.

View the recording at:

    https://asciinema.org/a/ZnWN4ThNo28cKyY6cRQl1QGWp

[root@testvm student]# asciinema play https://asciinema.org/a/ZnWN4ThNo28cKyY6cRQl1QGWp
~ Playback failed: JSON decoding error: Expecting value: line 1 column 1 (char 0)

If i open this link in browser it opens perfectly.
When i use cURL to download this rec i got redirection to amazon AWS S3 Storage and a raw binary data.
Can anyone explain me what i am doing wrong?

dmi3mis

**Comment by bl-ue** [comment] 2020-12-28 00:23
@dmi3mis this works for me:
```console
$ curl 'https://asciinema.org/a/ZnWN4ThNo28cKyY6cRQl1QGWp.json'
{
  "version": 1,
  "width": 154,
  "height": 42,
  "duration": 5.389626,
  "command": null,
  "title": null,
  "env": {
    "TERM": "xterm-256color",
    "SHELL": "/bin/bash"
  },
  "stdout": [
    [
      0.083707,
      "\u001b]0;root@testvm:/home/student\u0007\u001b[?1034h[root@testvm student]# "
    ],
    [
      1.565135,
      "t"
    ],
    [
      0.079776,
      "e"
    ],
    [
      0.172209,
      "s"
    ],
    [
      0.024767,
      "t"
    ],
...
```
Is that the command you're using?

**Comment by sickill** [comment] 2020-12-29 11:24
I cannot reproduce the problem. Are you still experiencing it @dmi3mis ?

**Comment by dmi3mis** [comment] 2020-12-29 11:33
I tested again and can not reproduce problem  too.
Please close this issue. Problem has gone.

**Comment by bl-ue** [comment] 2020-12-29 12:19
@dmi3mis You can close it yourself.  Click the close button at the bottom of this page.

**Closed** 2020-12-29 12:22 UTC
