### ISSUE TITLE
Allow pausing playback

### ISSUE THREAD

**Issue by zeenix** [asciinema/asciinema#242] opened 2017-11-23 15:41 UTC
While the server has supported this for a long time:

https://github.com/asciinema/asciinema-server/issues/127

it would be very nice to have this supported in the cmdline player as well.

**Comment by laughedelic** [comment] 2017-11-23 16:56
Duplicate of https://github.com/asciinema/asciinema/issues/133. Also see https://github.com/asciinema/asciinema/pull/231

**Closed** 2017-11-25 23:39 UTC

**Comment by sickill** [comment] 2017-11-25 23:48
Toggling pause with space + stepping a frame at a time with period just landed in develop branch and will be released in 2.0 🙂
