### ISSUE TITLE
Strange escape characters recording ptpython

### ISSUE THREAD

**Issue by tiagocoutinho** [asciinema/asciinema#192] opened 2017-02-19 06:12 UTC
I use asciinema to record a [ptpython](https://github.com/jonathanslenders/ptpython) console.
The recorded video shows what I assume are strange escape characters in each ptpython prompt.
I attach a simple record showing the problem [issue-ptpython.json.zip](https://github.com/asciinema/asciinema/files/785619/issue-ptpython.json.zip).
Here is what I used in the command line:
`$ asciinema rec -c "ptpython" -w 0.25 -t "Issue with ptpython" issue-ptpython.json`

To view the problem simply download the attached file and do
`$ asciinema play issue-ptpython.json`

I am using:
* linux mint 18
* CPython 3.6.0 (default, Feb  4 2017, 14:24:34) [GCC 5.4.0 20160609]
* asciinema 1.3.0
* [ptpython](https://github.com/jonathanslenders/ptpython) 0.35
* [prompt_toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) 1.0.13

**Comment by mattdeckard** [comment] 2017-03-24 15:47
I've duplicated this on OSX and confirmed it's a duplicate of #108 
When following the steps to duplicate, if you look in the `issue-ptpython.json` file that is generated, it contains two `CSI 6 n` (CPR) control sequences that are causing the terminal to respond with an escape sequence encoding the cursor position.

@tiagocoutinho, as a workaround you should be able to use the `fix-asciicast`script in [this gist](https://gist.github.com/mattdeckard/246edaa833191f69862a8591498e09c2) to fix your offending JSON files.

**Closed** 2017-03-25 12:40 UTC
